### ISSUE TITLE
Неправильно ищет имя игрока, который играл в игры каталога больше всего времени, если игрок добавлен не последним

### ISSUE THREAD

**Issue by VasiliyMalyukov** [WOVASYA/javaqa-team-diplom#1]
# Описание:
Неправильно ищет имя игрока, который играл в игры каталога больше времени, если игрок добавлен не последним.

# Локация дефекта:
https://github.com/WOVASYA/javaqa-team-diplom/blob/595f2529faab8c26a80af640aa5ba0f35de1f7b1/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения:
1. Открыть проект в IDEA;
2. Запустить из класса GameStoreTest тест shouldGetMostPlayerIfPlayerIsNotTheLast;
3. Посмотреть на вывод консоли.

*Ожидаемый результат:* Nikolay
*Фактический результат:* Petr

# Скриншот:
![image](https://user-images.githubusercontent.com/117832718/222105052-d13e05ef-21c8-41bc-8208-7f4df96935a4.png)

# Окружение:
Операционная система: Windows 10, x64
IDE: IntelliJ IDEA Community Edition 2022.3.1
Java: OpenJDK 11

**Comment by Natalia-Bondarenko** [comment]
## Описание
В ходе трейса было установлено, что метод getMostPlayer ищет имена правильно. Проблема в методе addPlayTime, который не суммирует время игрока, а перезаписывает старое значение в этой строчке:
`playedTime.put(playerName, playedTime.get(playerName))`

## Локация дефекта
https://github.com/WOVASYA/javaqa-team-diplom/blob/7d7776f6f9aad0464da73b19040ee0c8fcdc8c81/src/main/java/ru/netology/GameStore.java#L46-L48
