### ISSUE TITLE
При суммировании времени всех игроков, возвращает 0

### ISSUE THREAD

**Issue by VasiliyMalyukov** [WOVASYA/javaqa-team-diplom#2]
# Описание:
При суммировании всех часов всех игроков, которое они провели за играми каталога, возвращает 0

# Локация дефекта:
https://github.com/WOVASYA/javaqa-team-diplom/blob/71b2635c54f21e8b54e6c6e5394bacd6c0dedc0b/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения:
1. Открыть проект в IDEA;
2. Запустить из класса GameStoreTest тест shouldGetSumPlayedTime;
3. Посмотреть на вывод консоли.

*Ожидаемый результат:* 36
*Фактический результат:* 0

# Скриншот:
![image](https://user-images.githubusercontent.com/117832718/222106633-9d628957-dc76-4bc4-956a-bb4e13802b47.png)

# Окружение:
Операционная система: Windows 10, x64
IDE: IntelliJ IDEA Community Edition 2022.3.1
Java: OpenJDK 11

**Comment by Natalia-Bondarenko** [comment]
##Описание
Реализован метод getSumPlayedTime класса GameStore.

##Реализованный метод
https://github.com/WOVASYA/javaqa-team-diplom/blob/e0a481aeae480e79a4a1ef75ffb4f21e258eedb3/src/main/java/ru/netology/GameStore.java#L77-L82
