### ISSUE TITLE
Игры не добавляются в каталог GameStore

### ISSUE THREAD

**Issue by VasiliyMalyukov** [WOVASYA/javaqa-team-diplom#3]
# Описание:
Игры не добавляются в каталог GameStore

# Локация дефекта:
https://github.com/WOVASYA/javaqa-team-diplom/blob/71b2635c54f21e8b54e6c6e5394bacd6c0dedc0b/src/main/java/ru/netology/GameStore.java#L22-L26

# Шаги воспроизведения:
1. Открыть проект в IDEA;
2. Запустить из класса GameStoreTest тест shouldAddGame или тест shouldAddSeveralGames;
3. Посмотреть на вывод консоли.

*Ожидаемый результат:* true - игра добавлена в каталог
*Фактический результат:* false - игра не добавлена в каталог

# Скриншот:
![image](https://user-images.githubusercontent.com/117832718/222107961-2ec57823-9b72-4a8c-8d28-4abca822e8e6.png)

![image](https://user-images.githubusercontent.com/117832718/222108155-28b2bb0e-3179-4d7c-8a7f-82872623a7dc.png)

# Окружение:
Операционная система: Windows 10, x64
IDE: IntelliJ IDEA Community Edition 2022.3.1
Java: OpenJDK 11

**Comment by NataliaGvozdeva** [comment]
## Описание
Во время трейса работы теста shouldAddGame и shouldAddSeveralGames, оказалось, что метод publishGame корректно добавляет данные в католог games, т к игры в нём появляются.
Дефект был выявлен в методе containceGame, в котором цикл for начинался с индекса 1, а требовалось с 0, т к список начинается с 0. 
После исправлений тесты shouldAddGame и shouldAddSeveralGames проходят успешно.

## Локация дефекта
https://github.com/WOVASYA/javaqa-team-diplom/blob/595f2529faab8c26a80af640aa5ba0f35de1f7b1/src/main/java/ru/netology/GameStore.java#L32-L34

## Исправленный код
https://github.com/WOVASYA/javaqa-team-diplom/blob/147ee16c43ccb0f9cb7a35fb844c076a7238655f/src/main/java/ru/netology/GameStore.java#L32-L34

## Скриншоты
![image](https://user-images.githubusercontent.com/18085714/222778554-359f7e4c-300b-45b3-9244-8282001f888d.png)
![image](https://user-images.githubusercontent.com/18085714/222778792-0edaf1da-440c-46fd-9bdd-55a9bd30d45f.png)

**Comment by Natalia-Bondarenko** [comment]
## Описание 
В ходе трейса тестов shouldAddGame и shouldAddSeveralGames оказалось, что метод publishGame корректно заполняет каталок играми.
Дефект был выявлен в методе containsGame: цикл for начинал индексацию с 1, хотя требуется с 0, т к List нумеруется с 0.

## Локация дефекта
https://github.com/WOVASYA/javaqa-team-diplom/blob/147ee16c43ccb0f9cb7a35fb844c076a7238655f/src/main/java/ru/netology/GameStore.java#L32-L34
